### ISSUE TITLE
我下载磁力链的时候报认证错误，编译源码

### ISSUE THREAD

**Issue by zhiyou007** [yahch/aria2c-android-app#1]

**Comment by yahch** [comment]
贴个图看看？

**Comment by zhiyou007** [comment]
我把秘钥去了，你那个管理界面没连上aria2服务啊，没有用秘钥登录

**Comment by yahch** [comment]
管理界面不会自动连上服务，需要自己设置一下地址，秘钥

**Comment by zhiyou007** [comment]
下载还是不稳定啊，有没有稳定点的，我看那个迅雷组件好快，但好像不开放，不知道怎么搞的，你下个叫磁力TV的，用的就是那个，还能在线播，不知道什么技术

**Comment by qugang** [comment]
他自己有服务器做种的，和快播一样，把他们的trackers 拿到就好了。
